name: Update TV API Config

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install base58

      - name: Download and process config
        run: |
          # 下载配置文件
          curl -s -o config.json https://raw.githubusercontent.com/cmliussss2024/MoonTV/main/config.json
          
          # 压缩并进行base58编码
          python3 -c "
          import json
          import base58
          import sys
          
          # 读取并解析JSON
          with open('config.json', 'r', encoding='utf-8') as f:
              data = json.load(f)
          
          # 压缩JSON（去除空格和换行）
          compressed = json.dumps(data, separators=(',', ':'), ensure_ascii=False)
          
          # Base58编码
          encoded = base58.b58encode(compressed.encode('utf-8')).decode('ascii')
          
          # 写入文件
          with open('tvapi_config_yaml', 'w', encoding='utf-8') as f:
              f.write(encoded)
          
          print('Config file processed and encoded successfully')
          "

      - name: Check for changes and commit
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add tvapi_config_yaml
            
            # 检查是否有变更
            if git diff --cached --quiet; then
            echo "没有文件变更，跳过提交"
            else
            echo "检测到文件变更，开始提交"
            git commit -m "Downloaded file on $(date "+%Y/%m/%d %H:%M:%S")"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
            git push
            echo "提交完成"
            fi